[[task]]
  id = "client"
  type = "short"
  cmd = "go run -mod=mod cmd/client/main.go"

[[task]]
  id = "gen-all"
  type = "short"
  dependencies = ["gen-server", "gen-client"]

[[task]]
  id = "gen-server"
  type = "short"
  cmd = "oapi-codegen --config=configs/server.cfg.yml openapi-spec.yml"

[[task]]
  id = "gen-client"
  type = "short"
  cmd = "oapi-codegen --config=configs/client.cfg.yml openapi-spec.yml"

[[task]]
  id = "clean"
  type = "short"
  cmd = "rm -rf internal/server/generated internal/client/generated"
