// Code generated by genny; DO NOT EDIT.

package api

import (
	"context"

	"github.com/samsarahq/go/oops"
)

// ConditionAll returns a slice of all Condition, or an error if unsuccessful.
func (c *Client) ConditionAll(ctx context.Context) ([]*Condition, error) {
	res, err := allHelper(ctx, c, "conditions")
	if err != nil {
		return nil, oops.Wrapf(err, "unable to get resource list for conditions")
	}

	resList := []*Condition{}
	for _, resource := range res.Resources {
		parsedRes, err := c.ConditionByIndex(ctx, resource.Index)
		if err != nil {
			return nil, oops.Wrapf(err, "unable to get conditions with index %s for list", resource.Index)
		}
		resList = append(resList, parsedRes)
	}

	return resList, nil
}

// ConditionByIndex returns the Condition with the given index, or an error if unsuccessful.
func (c *Client) ConditionByIndex(ctx context.Context, index string) (*Condition, error) {
	res := apiCondition{}
	if err := byIndexHelper(ctx, c, &res, "conditions", index); err != nil {
		return nil, oops.Wrapf(err, "unable to get resource: conditions with index: %s", index)
	}
	return res.convert(), nil
}

