// Code generated by genny; DO NOT EDIT.

package api

// generated response type for api/ability-scores/{index}
type apiAbilityScore struct {
	Index    string         `json:"index"`
	Name     string         `json:"name"`
	FullName string         `json:"full_name"`
	Desc     []string       `json:"desc"`
	Skills   []APIReference `json:"skills"`
	Url      string         `json:"url"`
}

// generated response type for api/skills/{index}
type apiSkill struct {
	Index        string       `json:"index"`
	Name         string       `json:"name"`
	Desc         []string     `json:"desc"`
	AbilityScore APIReference `json:"ability_score"`
	Url          string       `json:"url"`
}

// generated response type for api/proficiencies/{index}
type apiProficiency struct {
	Index      string         `json:"index"`
	Type       string         `json:"type"`
	Name       string         `json:"name"`
	Classes    []APIReference `json:"classes"`
	Races      []APIReference `json:"races"`
	Url        string         `json:"url"`
	References []APIReference `json:"references"`
}

// generated response type for api/languages/{index}
type apiLanguage struct {
	Index           string   `json:"index"`
	Name            string   `json:"name"`
	Type            string   `json:"type"`
	TypicalSpeakers []string `json:"typical_speakers"`
	Script          string   `json:"script"`
	Url             string   `json:"url"`
}

// generated response type for api/classes/{index}
type apiClass struct {
	Index              string         `json:"index"`
	Name               string         `json:"name"`
	HitDie             int32          `json:"hit_die"`
	ProficiencyChoices []Choice       `json:"proficiency_choices"`
	Proficiencies      []APIReference `json:"proficiencies"`
	SavingThrows       []APIReference `json:"saving_throws"`
	StartingEquipment  URLRefString   `json:"starting_equipment"`
	ClassLevels        URLRefString   `json:"class_levels"`
	Subclasses         []APIReference `json:"subclasses"`
	Spellcasting       URLRefString   `json:"spellcasting"`
	Spells             URLRefString   `json:"spells"`
	Url                string         `json:"url"`
}

// generated response type for api/classes/{index}/subclasses/
type apiSubclassesForClass struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/classes/{index}/spells/
type apiSpellsForClass struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/classes/{index}/features/
type apiFeaturesForClass struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/classes/{index}/proficiencies/
type apiProficienciesForClass struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/classes/{index}/levels/
type apiLevelsForClass struct {
	Index               string                 `json:"index"`
	Level               int32                  `json:"level"`
	AbilityScoreBonuses int32                  `json:"ability_score_bonuses"`
	ProfBonus           int32                  `json:"prof_bonus"`
	FeatureChoices      []APIReference         `json:"feature_choices"`
	Features            []APIReference         `json:"features"`
	Spellcasting        map[string]interface{} `json:"spellcasting"`
	ClassSpecific       map[string]interface{} `json:"class_specific"`
	Class               APIReference           `json:"class"`
	Url                 string                 `json:"url"`
}

// generated response type for api/classes/{index}/levels/{integer 1-20}
type apiLevelForClass struct {
	Index               string                 `json:"index"`
	Level               int32                  `json:"level"`
	AbilityScoreBonuses int32                  `json:"ability_score_bonuses"`
	ProfBonus           int32                  `json:"prof_bonus"`
	FeatureChoices      []APIReference         `json:"feature_choices"`
	Features            []APIReference         `json:"features"`
	Spellcasting        map[string]interface{} `json:"spellcasting"`
	ClassSpecific       map[string]interface{} `json:"class_specific"`
	Class               APIReference           `json:"class"`
	Url                 string                 `json:"url"`
}

// generated response type for api/classes/{index}/levels/{integer 1-20}/features
type apiFeaturesForClassAndLevel struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/classes/{index}/levels/{integer 1-20}/spells
type apiSpellsForClassAndLevel struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/conditions/{index}
type apiCondition struct {
	Index string   `json:"index"`
	Name  string   `json:"name"`
	Desc  []string `json:"desc"`
	Url   string   `json:"url"`
}

// generated response type for api/damage-types/{index}
type apiDamageType struct {
	Index string   `json:"index"`
	Name  string   `json:"name"`
	Desc  []string `json:"desc"`
	Url   string   `json:"url"`
}

// generated response type for api/magic-schools/{index}
type apiMagicSchool struct {
	Index string `json:"index"`
	Name  string `json:"name"`
	Desc  string `json:"desc"`
	Url   string `json:"url"`
}

// generated response type for api/equipment-categories/{index}
type apiEquipmentCategory struct {
	Index     string         `json:"index"`
	Name      string         `json:"name"`
	Equipment []APIReference `json:"equipment"`
}

// generated response type for api/equipment/{index}
type apiWeapon struct {
	Index             string                 `json:"index"`
	Name              string                 `json:"name"`
	EquipmentCategory APIReference           `json:"equipment_category"`
	WeaponCategory    string                 `json:"weapon_category"`
	WeaponRange       string                 `json:"weapon_range"`
	CategoryRange     string                 `json:"category_range"`
	Cost              Cost                   `json:"cost"`
	Damage            map[string]interface{} `json:"damage"`
	Range             map[string]interface{} `json:"range"`
	Weight            int32                  `json:"weight"`
	Properties        []APIReference         `json:"properties"`
	Url               string                 `json:"url"`
}

// generated response type for api/equipment/{index}
type apiArmor struct {
	Index               string                 `json:"index"`
	Name                string                 `json:"name"`
	EquipmentCategory   APIReference           `json:"equipment_category"`
	ArmorCategory       string                 `json:"armor_category"`
	ArmorClass          map[string]interface{} `json:"armor_class"`
	StrMinimum          int32                  `json:"str_minimum"`
	StealthDisadvantage bool                   `json:"stealth_disadvantage"`
	Weight              int32                  `json:"weight"`
	Cost                Cost                   `json:"cost"`
	Url                 string                 `json:"url"`
}

// generated response type for api/equipment/{index}
type apiGear struct {
	Index             string       `json:"index"`
	Name              string       `json:"name"`
	EquipmentCategory APIReference `json:"equipment_category"`
	GearCategory      APIReference `json:"gear_category"`
	Cost              Cost         `json:"cost"`
	Weight            int32        `json:"weight"`
	Url               string       `json:"url"`
}

// generated response type for api/equipment/{index}
type apiEquipmentPack struct {
	Index             string         `json:"index"`
	Name              string         `json:"name"`
	EquipmentCategory APIReference   `json:"equipment_category"`
	GearCategory      APIReference   `json:"gear_category"`
	Cost              Cost           `json:"cost"`
	Contents          []APIReference `json:"contents"`
	Url               string         `json:"url"`
}

// generated response type for api/magic-items/{index}
type apiMagicItem struct {
	Index             string       `json:"index"`
	Name              string       `json:"name"`
	EquipmentCategory APIReference `json:"equipment_category"`
	Desc              []string     `json:"desc"`
}

// generated response type for api/races/{index}
type apiRaces struct {
	Index                 string         `json:"index"`
	Name                  string         `json:"name"`
	Speed                 int32          `json:"speed"`
	AbilityBonuses        []AbilityBonus `json:"ability_bonuses"`
	Alignment             string         `json:"alignment"`
	Age                   string         `json:"age"`
	Size                  string         `json:"size"`
	SizeDescription       string         `json:"size_description"`
	StartingProficiencies []APIReference `json:"starting_proficiencies"`
	Languages             []APIReference `json:"languages"`
	LanguageDesc          string         `json:"language_desc"`
	Traits                []APIReference `json:"traits"`
	Subraces              APIReference   `json:"subraces"`
	Url                   string         `json:"url"`
}

// generated response type for api/races/{index}/subraces/
type apiSubracesForRace struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/races/{index}/proficiencies/
type apiProficienciesForRace struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/races/{index}/traits/
type apiTraitsForRace struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/subraces/{index}
type apiSubrace struct {
	Index          int32          `json:"index"`
	Name           string         `json:"name"`
	Race           APIReference   `json:"race"`
	Desc           string         `json:"desc"`
	AbilityBonuses []AbilityBonus `json:"ability_bonuses"`
	Languages      []APIReference `json:"languages"`
	Traits         []APIReference `json:"traits"`
	Url            string         `json:"url"`
}

// generated response type for api/subraces/{index}/traits/
type apiTraitsForSubrace struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/subraces/{index}/proficiencies/
type apiProficienciesForSubrace struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/subclasses/{index}
type apiSubclass struct {
	Index          string        `json:"index"`
	Class          APIReference  `json:"class"`
	Name           string        `json:"name"`
	SubclassFlavor string        `json:"subclass_flavor"`
	Desc           string        `json:"desc"`
	Spells         []interface{} `json:"spells"`
	SubclassLevels APIReference  `json:"subclass_levels"`
	Url            string        `json:"url"`
}

// generated response type for api/subclasses/{index}/features/
type apiFeaturesForSubclass struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/subclasses/{index}/levels/
type apiLevelsForSubclass struct {
	Level          int32          `json:"level"`
	FeatureChoices []APIReference `json:"feature_choices"`
	Features       []APIReference `json:"features"`
	Class          APIReference   `json:"class"`
	Subclass       APIReference   `json:"subclass"`
	Url            string         `json:"url"`
	Index          string         `json:"index"`
}

// generated response type for api/subclasses/{index}/levels/{integer 1-20}
type apiLevelForSubclass struct {
	Level          int32          `json:"level"`
	FeatureChoices []APIReference `json:"feature_choices"`
	Features       []APIReference `json:"features"`
	Classe         APIReference   `json:"classe"`
	Subclass       APIReference   `json:"subclass"`
	Url            string         `json:"url"`
	Index          string         `json:"index"`
}

// generated response type for api/subclasses/{index}/levels/{integer 1-20}/features
type apiFeaturesForSubclassAndLevel struct {
	Count   int32          `json:"count"`
	Results []APIReference `json:"results"`
}

// generated response type for api/traits/{index}
type apiTrait struct {
	Index              int32          `json:"index"`
	Races              []APIReference `json:"races"`
	Subraces           []APIReference `json:"subraces"`
	Name               string         `json:"name"`
	Desc               []string       `json:"desc"`
	Proficiencies      []APIReference `json:"proficiencies"`
	ProficiencyChoices []Choice       `json:"proficiency_choices"`
	Url                string         `json:"url"`
}

// generated response type for api/weapon-properties/{index}
type apiWeaponProperty struct {
	Index int32    `json:"index"`
	Name  string   `json:"name"`
	Desc  []string `json:"desc"`
	Url   string   `json:"url"`
}

