# NOT A PRIORITY
# This is a placeholder for now, the client generation is more interesting.
package: server
output: internal/server/generated/server.gen.go
generate:
  gin-server: true
  models: true
compatibility:
  always-prefix-enum-values: true
output-options:
  name-normalizer: ToCamelCaseWithInitialisms
