package: server
output: internal/server/generated/server.gen.go
generate:
  gin-server: true
  embedded-spec: true
  strict-server: true
  models: true
compatibility:
  always-prefix-enum-values: true
output-options:
  name-normalizer: ToCamelCaseWithInitialisms
